### ISSUE TITLE
Request timed out for the ETA API call

### ISSUE THREAD

**Issue by faiyip** [winstonma/MMM-HK-KMB#6]
hi,
  I am getting the following error from my server, can you correct it?

[2020-08-17 03:17:36.944] [LOG]    { RequestError: connect ETIMEDOUT 52.139.174.116:80
    at ClientRequest.request.once (/var/www/magicmirror/MagicMirror/modules/MMM-HK-KMB/node_modules/got/dist/source/core/index.js:891:25)
    at Object.onceWrapper (events.js:286:20)
    at ClientRequest.emit (events.js:203:15)
    at ClientRequest.origin.emit.args (/var/www/magicmirror/MagicMirror/modules/MMM-HK-KMB/node_modules/@szmarczak/http-timer/dist/source/index.js:39:20)
    at Socket.socketErrorListener (_http_client.js:401:9)
    at Socket.emit (events.js:198:13)
    at emitErrorNT (internal/streams/destroy.js:91:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1107:14)
  name: 'RequestError',
  code: 'ETIMEDOUT',
  timings:
   { start: 1597648624363,
     socket: 1597648624363,
     lookup: 1597648624366,
     connect: undefined,
     secureConnect: undefined,
     upload: undefined,
     response: undefined,
     end: undefined,
     error: 1597648656943,
     abort: undefined,
     phases:
      { wait: 0,
        dns: 3,
        tcp: undefined,
        tls: undefined,
        request: undefined,
        firstByte: undefined,
        download: undefined,
        total: 32580 } } }

**Comment by winstonma** [comment]
Just checked that the ETA method is not accessible

Let me check the alternatives

**Comment by winstonma** [comment]
Commit [f234fc01879474f9e6f1129cc856bf42ba011c2b](https://github.com/winstonma/MMM-HK-KMB/commit/f234fc01879474f9e6f1129cc856bf42ba011c2b) is a quick fix.

Please let me know if you still see any problem. Thanks

**Comment by faiyip** [comment]
hi,
  I clone the repository again, and install aes-js and node-schedule.
  But I am still getting the following error.

  {
module: 'MMM-HK-KMB',
position: 'top_left',
config: {
stops: [
{
stopID: 'TA21-N-1850-0', // Which stop would you like to have displayed?
}
]
}
},

Thanks
Fai


[2020-08-18 07:06:27.387] [ERROR]  (node:14758)
UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'body' of
undefined
    at
/var/www/magicmirror/MagicMirror/modules/MMM-HK-KMB/node_helper.js:48:79
    at process._tickCallback (internal/process/next_tick.js:68:7)
[2020-08-18 07:06:27.389] [ERROR]  (node:14758)
UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error
originated either by throwing inside of an async function without a catch
block, or by rejecting a promise which was not handled with .catch().
(rejection id: 1)
[2020-08-18 07:06:27.389] [ERROR]  (node:14758) [DEP0018]
DeprecationWarning: Unhandled promise rejections are deprecated. In the
future, promise rejections that are not handled will terminate the Node.js
process with a non-zero exit code.
[2020-08-18 07:06:39.335] [ERROR]  Whoops! There was an uncaught
exception...
[2020-08-18 07:06:39.336] [ERROR]  TypeError: Cannot read property 'filter'
of undefined
    at Class.getStopInfo
(/var/www/magicmirror/MagicMirror/modules/MMM-HK-KMB/node_helper.js:98:42)
    at payload.config.map
(/var/www/magicmirror/MagicMirror/modules/MMM-HK-KMB/node_helper.js:58:14)
    at Array.map (<anonymous>)
    at Class.socketNotificationReceived
(/var/www/magicmirror/MagicMirror/modules/MMM-HK-KMB/node_helper.js:57:22)
    at Socket.<anonymous>
(/var/www/magicmirror/MagicMirror/js/node_helper.js:112:11)
    at Socket.emit (events.js:198:13)
    at /var/www/magicmirror/MagicMirror/node_modules/
socket.io/lib/socket.js:528:12
    at process._tickCallback (internal/process/next_tick.js:61:11)
[2020-08-18 07:06:39.341] [ERROR]  MagicMirror will not quit, but it might
be a good idea to check why this happened. Maybe no internet connection?
[2020-08-18 07:06:39.342] [ERROR]  If you think this really is an issue,
please open an issue on GitHub:
https://github.com/MichMich/MagicMirror/issues
[2020-08-18 07:06:39.539] [ERROR]  error: cannot open .git/FETCH_HEAD:
Permission denied


<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by winstonma** [comment]
Hmm... based on your description that's not the ETA fetcher error described earlier. I would spend some time to take a look.

But the happy path (no connection error) should work. Would you mind restarting MagicMirror again? Thanks for the help @faiyip

**Comment by faiyip** [comment]
hi ,
  Yes, I restarted the magic mirror many times, but no help. and in fact, I
am trying to figure out the ajax call like the one below.

https://search.kmb.hk/KMBWebSite/Function/FunctionRequest.ashx?action=getRoutesInStop&bsiCode=TA21-N-1850-0

Thanks
Fai

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by winstonma** [comment]
This is the API result from my side:

https://search.kmb.hk/KMBWebSite/Function/FunctionRequest.ashx?action=getRoutesInStop&bsiCode=TA21-N-1850-0
> {"data":["72      ","81      ","85      ","88      ","283     ","72A     ","80K     ","88K     "],"result":true}

Did you get the result?

**Comment by faiyip** [comment]
hi ,
  Yes, I got the same result for this API

But
http://search.kmb.hk/KMBWebSite/Function/FunctionRequest.ashx?acton=getallstops
return nothing.


Thanks
Fai

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by winstonma** [comment]
Finally saw the problem

`https` works but not `http`. Just make one commit. Thanks again

**Comment by faiyip** [comment]
hi,
  I am still seeing  errors.

Thank you very much for your quick response.
Fai



2020-08-18 09:21:56.581] [LOG]    Module helper loaded: MMM-HK-KMB
[2020-08-18 09:21:56.582] [LOG]    No helper found for module:
MMM-Worldclock.
[2020-08-18 09:21:56.583] [LOG]    All module helpers loaded.
[2020-08-18 09:21:56.723] [LOG]    Starting server on port 8080 ...
[2020-08-18 09:21:56.741] [LOG]    Server started ...
[2020-08-18 09:21:56.743] [LOG]    Connecting socket for: updatenotification
[2020-08-18 09:21:56.744] [LOG]    Connecting socket for: MMM-LunarDate
[2020-08-18 09:21:56.746] [LOG]    Connecting socket for: calendar
[2020-08-18 09:21:56.747] [LOG]    Starting node helper for: calendar
[2020-08-18 09:21:56.748] [LOG]    Connecting socket for: newsfeed
[2020-08-18 09:21:56.749] [LOG]    Starting node helper for: newsfeed

*[2020-08-18 09:21:56.750] [LOG]    Connecting socket for:
MMM-HK-KMB[2020-08-18 09:21:56.752] [LOG]    Starting node helper for:
MMM-HK-KMB*
[2020-08-18 09:21:56.763] [LOG]    Sockets connected & modules started ...
[2020-08-18 09:21:56.764] [LOG]
Ready to go! Please point your browser to: http://0.0.0.0:8080
[



*2020-08-18 09:21:56.927] [ERROR]  (node:1517)
UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'body' of
undefined    at
/var/www/magicmirror/MagicMirror/modules/MMM-HK-KMB/node_helper.js:48:79
at process._tickCallback (internal/process/next_tick.js:68:7)[2020-08-18
09:21:56.928] [ERROR]  (node:1517) UnhandledPromiseRejectionWarning:
Unhandled promise rejection. This error originated either by throwing
inside of an async function without a catch block, or by rejecting a
promise which was not handled with .catch(). (rejection id: 1)[2020-08-18
09:21:56.929] [ERROR]  (node:1517) [DEP0018] DeprecationWarning: Unhandled
promise rejections are deprecated. In the future, promise rejections that
are not handled will terminate the Node.js process with a non-zero exit
code.*
[2020-08-18 09:22:07.106] [LOG]    Create new news fetcher for url:
https://www.cnbc.com/id/15837362/device/rss/rss.html - Interval: 300000
[2020-08-18 09:22:07.173] [LOG]    LunarDate:
http://apis.data.go.kr/B090041/openapi/service/LrsrCldInfoService/getLunCalInfo?ServiceKey=9qwEEJZunbv%2BuXNPlIThdHrl6%2Bkr8Csx%2BBzknlYwJCq%2FL2bPhpYdd5gPRy0nvKBrmoVSCmR15z3B0G5s1DbqTg%3D%3D&solYear=2020&solMonth=08&solDay=18
[2020-08-18 09:22:07.183] [LOG]    Create new calendar fetcher for url:
http://www.1823.gov.hk/common/ical/tc.ics - Interval: 300000
[2020-08-18 09:22:07.191] [LOG]    Create new calendar fetcher for url:
https://calendar.google.com/calendar/ical/faiyip.63%40gmail.com/private-9117053c06e5e3e2f1d6c31eb383bcbb/basic.ics
- Interval: 300000
[2020-08-18 09:22:07.202] [LOG]    Create new calendar fetcher for url:
http://www.calendarlabs.com/ical-calendar/ics/76/US_Holidays.ics -
Interval: 300000
[2020-08-18 09:22:07.207] [LOG]    Create new news fetcher for url:
http://rthk9.rthk.hk/rthk/news/rss/c_expressnews_clocal.xml - Interval:
300000
[2020-08-18 09:22:07.239] [LOG]    Create new stop fetcher for stopID:
TA21-N-1850-0












*[2020-08-18 09:22:07.259] [ERROR]  Whoops! There was an uncaught
exception...[2020-08-18 09:22:07.260] [ERROR]  TypeError: Cannot read
property 'filter' of undefined    at Class.getStopInfo
(/var/www/magicmirror/MagicMirror/modules/MMM-HK-KMB/node_helper.js:98:42)
  at payload.config.map
(/var/www/magicmirror/MagicMirror/modules/MMM-HK-KMB/node_helper.js:58:14)
  at Array.map (<anonymous>)    at Class.socketNotificationReceived
(/var/www/magicmirror/MagicMirror/modules/MMM-HK-KMB/node_helper.js:57:22)
  at Socket.<anonymous>
(/var/www/magicmirror/MagicMirror/js/node_helper.js:112:11)    at
Socket.emit (events.js:198:13)    at
/var/www/magicmirror/MagicMirror/node_modules/socket.io/lib/socket.js:528:12
<http://socket.io/lib/socket.js:528:12>    at process._tickCallback
(internal/process/next_tick.js:61:11)[2020-08-18 09:22:07.267] [ERROR]
 MagicMirror will not quit, but it might be a good idea to check why this
happened. Maybe no internet connection?[2020-08-18 09:22:07.268] [ERROR]
 If you think this really is an issue, please open an issue on GitHub:
https://github.com/MichMich/MagicMirror/issues
<https://github.com/MichMich/MagicMirror/issues>*[2020-08-18 09:22:07.286]
[INFO]   Checking git for module: MMM-LunarDate
[2020-08-18 09:22:07.317] [INFO]   Checking git for module: MMM-HK-KMB
[2020-08-18 09:22:07.337] [INFO]   Checking git for module: MMM-Worldclock

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by winstonma** [comment]
Does https://search.kmb.hk/KMBWebSite/Function/FunctionRequest.ashx?action=getallstops work for you?

If yes then I would expect the error will be gone by one `git pull`. Hmm

**Comment by faiyip** [comment]
hi,

getallstops works, and I did the pull, and even removed the module and
clone it again.

But I am still getting errors.

Thanks
Fai


fai@pi205:/var/www/magicmirror/MagicMirror/modules/MMM-HK-KMB $ git pull
Already up to date.
fai@pi205:/var/www/magicmirror/MagicMirror/modules/MMM-HK-KMB $ cd ../..
fai@pi205:/var/www/magicmirror/MagicMirror $ npm run server
npm WARN npm npm does not support Node.js v10.21.0
npm WARN npm You should probably upgrade to a newer version of node as we
npm WARN npm can't make any promises that npm will work with this version.
npm WARN npm Supported releases of Node.js are the latest release of 4, 6,
7, 8, 9.
npm WARN npm You can find the latest version at https://nodejs.org/

> magicmirror@2.12.0 server /var/www/magicmirror/MagicMirror
> node ./serveronly

[2020-08-18 10:01:54.356] [LOG]    Starting MagicMirror: v2.12.0
[2020-08-18 10:01:54.372] [LOG]    Loading config ...
[2020-08-18 10:01:54.378] [LOG]    Loading module helpers ...
[2020-08-18 10:01:54.380] [LOG]    No helper found for module:
MMM-auto-refresh.
[2020-08-18 10:01:54.381] [LOG]    No helper found for module: alert.
[2020-08-18 10:01:54.438] [LOG]    Initializing new module helper ...
[2020-08-18 10:01:54.439] [LOG]    Module helper loaded: updatenotification
[2020-08-18 10:01:54.440] [LOG]    No helper found for module: clock.
[2020-08-18 10:01:54.870] [LOG]    Initializing new module helper ...
[2020-08-18 10:01:54.871] [LOG]    Module helper loaded: MMM-LunarDate
[2020-08-18 10:01:54.871] [LOG]    No helper found for module:
weatherforecast.
[2020-08-18 10:01:54.948] [LOG]    Initializing new module helper ...
[2020-08-18 10:01:54.949] [LOG]    Module helper loaded: calendar
[2020-08-18 10:01:54.979] [LOG]    Initializing new module helper ...
[2020-08-18 10:01:54.980] [LOG]    Module helper loaded: newsfeed
[2020-08-18 10:01:55.104] [LOG]    Initializing new module helper ...
[2020-08-18 10:01:55.105] [LOG]    Module helper loaded: MMM-HK-KMB
[2020-08-18 10:01:55.106] [LOG]    No helper found for module:
MMM-Worldclock.
[2020-08-18 10:01:55.106] [LOG]    All module helpers loaded.
[2020-08-18 10:01:55.237] [LOG]    Starting server on port 8080 ...
[2020-08-18 10:01:55.263] [LOG]    Server started ...
[2020-08-18 10:01:55.264] [LOG]    Connecting socket for: updatenotification
[2020-08-18 10:01:55.266] [LOG]    Connecting socket for: MMM-LunarDate
[2020-08-18 10:01:55.267] [LOG]    Connecting socket for: calendar
[2020-08-18 10:01:55.268] [LOG]    Starting node helper for: calendar
[2020-08-18 10:01:55.268] [LOG]    Connecting socket for: newsfeed
[2020-08-18 10:01:55.269] [LOG]    Starting node helper for: newsfeed
[2020-08-18 10:01:55.270] [LOG]    Connecting socket for: MMM-HK-KMB
[2020-08-18 10:01:55.271] [LOG]    Starting node helper for: MMM-HK-KMB
[2020-08-18 10:01:55.282] [LOG]    Sockets connected & modules started ...
[2020-08-18 10:01:55.283] [LOG]
Ready to go! Please point your browser to: http://0.0.0.0:8080
[2020-08-18 10:01:55.446] [ERROR]  (node:1983)
UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'body' of
undefined
    at
/var/www/magicmirror/MagicMirror/modules/MMM-HK-KMB/node_helper.js:48:79
    at process._tickCallback (internal/process/next_tick.js:68:7)
[2020-08-18 10:01:55.448] [ERROR]  (node:1983)
UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error
originated either by throwing inside of an async function without a catch
block, or by rejecting a promise which was not handled with .catch().
(rejection id: 1)
[2020-08-18 10:01:55.448] [ERROR]  (node:1983) [DEP0018]
DeprecationWarning: Unhandled promise rejections are deprecated. In the
future, promise rejections that are not handled will terminate the Node.js
process with a non-zero exit code.



<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by faiyip** [comment]
hi,

Does
https://search.kmb.hk/KMBWebSite/Function/FunctionRequest.ashx?action=getallstops
work
for you?
Well, I see the problem.  If I wget this URL, I got a 16MB response.
However, it doesn't look like your module will get the response.

Thanks
Fai




<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by winstonma** [comment]
That very strange... hmm...

First of all I got a 1.8MB fille from the getallstops API. Secondly the program uses the responses. In fact I added the following line

```
        console.log(body.data.stops.length);  // Added line
        this.AllStopsInfo = body.data.stops;
```

And saw that there are 6287 of bus stop data is being fetched.

For the `wget` command did you run in on your RPi?

**Comment by faiyip** [comment]
hi ,
  Yes, it is strange.

  Yes, I did the wget in my raspberry pi

wget "
https://search.kmb.hk/KMBWebSite/Function/FunctionRequest.ashx?action=getallstops
"
this works.

Yes, you are correct, the response size is about 1.8MB.


I also changed the node_helper.js, and apparently, the result wasn't return
in a json data structure.

Thanks
Fai



  getStopsInfo: async function () {
    const self = this;

    const routeStopCheckUrl = "
https://search.kmb.hk/KMBWebSite/Function/FunctionRequest.ashx?action=getallstops
";

    const parseQueryString = {
      action: "getallstops"
    };

    (async () => {
      try {
        const { body } = await got.post(routeStopCheckUrl, {
          responseType: 'json',
        });
        console.log( "body length:" + body.length );
        var json_body = JSON.parse( body );
        this.AllStopsInfo = json_body.data.stops;
      } catch (error) {
        console.log("Error obtaining BusRoute connections: " + error );
        this.AllStopsInfo = [];
      }
    })();
  },







<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by winstonma** [comment]
Yes I guess so.

Maybe tomorrow I will try to give you the code snipper using `response` instead of `got`.

Thanks for your checking.

**Comment by faiyip** [comment]
hi ,
   One more thing, there's no error message, but at the same time, there's
no output.

My config for your module is "top_left" position, and it should be under
the calendar. but currently, there's nothing, and I waited a minute, hoping
the refresh will fix it, but getDom wasn't called after a minute.

Thanks
Fai


<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by winstonma** [comment]
AFAIK if getallstops couldn't get the result, it is very likely the rest would not be working.

Alternatively could you try to get rid of the API call and try the hard code way?

>     /*
>     (async () => {
>       try {
>         const { body } = await got.post(routeStopCheckUrl, {
>           searchParams: parseQueryString,
>           responseType: 'json'
>         });
>         this.AllStopsInfo = body.data.stops;
>       } catch (error) {
>         console.log("Error obtaining BusRoute connections: " + error.response.body);
>         this.AllStopsInfo = [];
>       }
>     })();
>     */
>     this.AllStopsInfo = [{ "EName": "MEI TAO HOUSE", "x": "836439.25000000", "ELocation2": "NEAR MEI TAO HOUSE", "ELocation1": "TAI PO RD", "CLocation2": "", "ELocation3": "", "CName": "美桃樓", "BSICode": "TA21-N-1850-0", "y": "826468.75000000", "CLocation3": "", "CLocation1": "大埔道美桃樓對出" }]

Also you need to include `TA21-N-1850-0` in config.js.

If you saw something on the screen then it is another problem.

In addition, I found another ETA fetch problem but if you should see something on your screen.

**Comment by faiyip** [comment]
hi ,
  I see nothing with the hard code.
  Yes, I think you are right, the etafetcher is not being called.

Thanks for working on it.
Fai

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by winstonma** [comment]
Hmm... it is extremely weird that all API suddenly won't work at the same time.

**Comment by faiyip** [comment]
hi,
  I did an update on the module  this morning, and it is working.

However, the translation somehow translate to German for whatever reason,
and I had to disabled it.  I had two bus stops that I wanted to show, and
keep them as two config items, but now they are showing twice.  Please take
a look at the attached pictures.

Thanks
Fai


<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by winstonma** [comment]
Good to hear but it is weird as I didn't update the getallstops API call

Also would you mind attaching the screenshot again?

For showing two stops in the meantime you can use

```
			module: 'MMM-HK-KMB',
			position: 'top_right',
			config: {
				stops: [
					{
						stopID: 'HO06-S-1250-0',		// Which stop would you like to have displayed?	
					},
					{
						stopID: 'KW16-W-2200-0',		// Which stop would you like to have displayed?	
					}
				]
			}
```

**Comment by faiyip** [comment]
magic mirror told me I was two version behind on your module, and that's
why I did an update on the module.

Here's the attachments again.

Thanks
Fai

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by winstonma** [comment]
Yeah I did 2 commit yesterday but it has nothing to do with the `getallstops` API call.

For translation did you set the following in `config.js`?

> 	language: "en",

Sorry I still have no access to the screenshot. Would you mind posting the screenshot though Github send me the photo URL?

**Comment by faiyip** [comment]
I used "zh-hk" , and "zh"

https://drive.google.com/file/d/14cuvBiRNo9da4IsjjCxExb7F-uVl1S9c/view?usp=sharing
https://drive.google.com/file/d/1nRgdun8SIYHCNlaw82PapJmgcWo_acmN/view?usp=sharing
https://drive.google.com/file/d/1GZ7DmWRnFBlbIEaBXtJ3ScJ94ygTi03O/view?usp=sharing

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by winstonma** [comment]
I got this error

![image](https://user-images.githubusercontent.com/1215090/90601588-098e1900-e22b-11ea-93d4-2cbcdda9c53a.png)

**Comment by faiyip** [comment]
hi ,
  I am sorry, I updated the permission.

Thanks
Fai

**Comment by winstonma** [comment]
I see

@faiyip, I opened a new [issue](https://github.com/winstonma/MMM-HK-KMB/issues/7) regarding to this multiple stops being shown problem. Please feel free to take a look and comment.

One last thing. May I know the  version of `got` running in your `package.json`?

**Comment by faiyip** [comment]
got is 11.5.2

Thanks
Fai

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by winstonma** [comment]
In this issue I fixed the ETA API call because KMB modified the API calling method. Still, I really have no idea why the `getallstops` not working yesterday.

If the ETA is working ATM then please close this ticket. Thanks

**Comment by faiyip** [comment]
ETA is working now
